/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./components/AppBackground.vue')['default']
    AppNav: typeof import('./components/AppNav.vue')['default']
    ColorPalette: typeof import('./components/ColorPalette.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelector: typeof import('./components/ThemeSelector.vue')['default']
    TypographyDemo: typeof import('./components/TypographyDemo.vue')['default']
    UiButton: typeof import('./components/ui/Button.vue')['default']
    UiCard: typeof import('./components/ui/Card.vue')['default']
  }
}
